[custom]
#地址：https://raw.githubusercontent.com/Pel0915/clash/refs/heads/main/CLASH/Clash_acyun.ini
;规则集定义
ruleset=🟢 直连,https://raw.githubusercontent.com/Pel0915/clash/refs/heads/main/CLASH/Direct.list
ruleset=🤖 AI,https://raw.githubusercontent.com/Pel0915/clash/main/AI.list
ruleset=🟢 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🟢 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🟢 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🟢 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🟢 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/CMB/CMB.list
ruleset=🟢 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ICBC/ICBC.list
ruleset=🟢 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/CCB/CCB.list
ruleset=👨🏿‍💻 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.list
ruleset=👨🏿‍💻 GitHub,clash-classic:https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GitHub/GitHub.yaml
ruleset=🚂 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
ruleset=🪟 Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=🎵 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎥 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=🎞️ 国内媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🟢 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🟢 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🟢 直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🟢 直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China.list
ruleset=🟢 直连,[]GEOSITE,CN
ruleset=🚀 节点选择,[]GEOSITE,geolocation-!cn
ruleset=🟢 直连,[]GEOIP,CN,no-resolve
ruleset=🐟 漏网之鱼,[]FINAL
;策略组定义
#`[]🐸 手动切换`[]🦅 美国节点`[]🏳️‍🌈 美国均衡`[]♻️ 自动选择`[]DIRECT`[]REJECT（均衡`load-balance、手动切换`select）
custom_proxy_group=🐸 手动切换`select`.*`^((?!(亿分|德国Hy2|×1|优化|①|距离下次|英国Hy2 ×0)).)*$`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=📹 YouTube`select`[]🦅 美国节点`[]🏳️‍🌈 美国均衡`[]🐸 手动切换
custom_proxy_group=🤖 AI`select`[]🐸 手动切换`[]🦅 美国节点
custom_proxy_group=🎵 TikTok`select`[]🦅 美国节点`[]🏳️‍🌈 美国均衡`[]🐸 手动切换
custom_proxy_group=📲 Telegram`select`[]🐸 手动切换`[]♻️ 自动选择
custom_proxy_group=🌍 国外媒体`select`[]🐸 手动切换`[]🦅 美国节点
custom_proxy_group=🦅 美国节点`select`(?=.*(美国))^((?!(优化|亿分)).)*$
custom_proxy_group=🚀 节点选择`select`[]🐸 手动切换`[]🦅 美国节点`[]🏳️‍🌈 美国均衡
custom_proxy_group=🚂 Google`select`[]🐸 手动切换`[]🦅 美国节点`[]🏳️‍🌈 美国均衡
custom_proxy_group=👨🏿‍💻 GitHub`select`[]🐸 手动切换`[]🏳️‍🌈 美国均衡
custom_proxy_group=🎥 Netflix`url-test`(?=.*(香港|美国Ⅰ|德国Ⅰ|英国Ⅰ|日本|新加坡|))`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🚀 节点选择`select`[]DIRECT`[]🐸 手动切换
custom_proxy_group=🟢 直连`select`[]DIRECT`[]🐸 手动切换
custom_proxy_group=🪟 Microsoft`select`[]🦅 美国节点`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🐸 手动切换`[]DIRECT`[]🦅 美国节点
custom_proxy_group=🏳️‍🌈 美国均衡`load-balance`(?=.*(美国))`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=♻️ 自动选择`url-test`^((?!(亿分|德国Hy2 ×1|优化|①|距离下次|英国Hy2 ×0)).)*$`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🍎 Apple`select`[]🐸 手动切换`[]DIRECT
custom_proxy_group=🎞️ 国内媒体`select`[]DIRECT
#custom_proxy_group=🦄 亚马逊`select`[]DIRECT
;启用自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
